version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "8800:8080"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    ipam:
      config:
        - subnet: 172.80.0.0/16
